version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  java: circleci/openjdk:11-browsers-legacy

workflows:
  maven_test:
    jobs:
     
      - maven/test # checkout, build, test, and upload test results
